import React from 'react'
import CourseList from '../project_1_coursezone/components/CourseList'

export const metadata = {
  title: "CourseZon Project",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
     <CourseList />
    </div>
  )
}

export default page
  